PROGRAM PROJ2
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!   PRJOECT II: THE STRUCTURE OF WHITE DWARF STARS
!   USES THE CENTRAL DENSITY OF A STAR TO DETERMINE
!   THE TOTAL MASS, RADIUS, GRAVITATIONAL ENERGY,
!   KINETIC ENERGY OF ELECTRONS AND TOTAL ENERGY.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
IMPLICIT NONE
    REAL :: RHO                     !SCALED RHO
    REAL :: RHO1,RHO2               !INITIAL AND FINAL RHO
    REAL :: RHO0                    !RHO SCALING FACTOR
    REAL :: YE                      !ELECTRON TO NUCLEON RATIO
    REAL :: H                       !LOGARITHMIC STEP FOR RHO
    INTEGER :: I                    !COUNTER
    INTEGER :: IMAX                 !NUMBER OF MODELS

10  PRINT *,'ENTER THE VALUE OF YE [0 < YE <= 1]'
    READ *,YE
    PRINT *,'WORKING VALUES IN KG/M^3 [1E8 < RHO <= 1E18]'
20  PRINT *,'ENTER THE INTITIAL DENSITY'
    READ *,RHO1
    PRINT *,'ENTER THE FINAL DENSITY'
    READ *,RHO2
    PRINT *,'ENTER THE NUMBER OF POINTS'
    READ *,IMAX
!MAKES SURE THAT 0 < YE <= 1
    IF (YE > 1.0 .OR. YE <= 0) THEN
        PRINT *,'0 < YE <= 1'
        GOTO 10
    END IF
!MAKES SURE THAT RHO2 > RHO1
    IF (RHO2 <= RHO1)THEN
        PRINT *,'FINAL DENSITY > INITIAL'
        GOTO 20
    END IF
!SCALES RHO. H IS SCALED LOGARITHMICALLY BETWEEN RHO INTITAL AND RHO FINAL
    RHO0 = 9.79E8/YE
    RHO1 = RHO1/RHO0
    RHO2 = RHO2/RHO0
    H = LOG(RHO2-RHO1)/(IMAX-1)

    DO I=0,IMAX-1
        RHO = EXP(I*H)+RHO1-1.0
        PRINT *,I+1
        PRINT *,'ELECTRON TO NUCLEON =',YE
        PRINT *,'CENTRAL DENSITY     =',RHO*RHO0,'         KG/M^3'
        CALL STEP2(RHO,YE)
    END DO
    GOTO 10
END PROGRAM

SUBROUTINE STEP2(RHO,YE)
IMPLICIT NONE
    REAL :: R                       !RADIUS OF THE STAR
    REAL :: RHO                     !DENSITY OF THE STAR
    REAL :: KRHO1,KRHO2,KRHO3,KRHO4 !DENSITY TERMS FOR THE RUNGE-KUTTA
    REAL :: DRHO                    !DERIVATIVE OF RHO WITH RESPECT TO RADIUS
    REAL :: M                       !MASS OF THE STAR
    REAL :: KM1,KM2,KM3,KM4         !MASS TERMS FOR THE RUNGE-KUTTA
    REAL :: DM                      !DERIVATIVE OF MASS WITH RESPECT TO RADIUS
    REAL :: DR                      !RADIAL STEP
    REAL :: KINETIC                 !KINETIC AND REST ENERGY OF ELECTRONS
    REAL :: GRAV                    !GRAVITATIONAL ENERGY OF STAR
    REAL :: EPSRHO                  !EPSILON FROM EQUATION II.10A
    REAL :: YE                      !NUMBER OF ELECTRONS PER NUCLEON
    INTEGER :: I                    !COUNTER
!SETS DR. MAKES IT SMALLER AS RHO INCREASES
    DR = .00001/RHO**(1.0/3.0)
    PRINT *,'RADIAL STEP         =',DR
!SETS VALUES TO 0
    I = 0
    M = 0.0
    KINETIC = 0.0
    GRAV = 0.0
    DO WHILE (RHO > .0001)
!DO LOOP WHICH PERFORMS THE RUNGE-KUTTA 4 ALGORITH TO FIND THE DENSITY AND MASS
!AT GIVEN VALUES OF R. ENDS WHEN RHO BECOMES < .0001
        I = I+1
!FINDS K1 FOR EACH EQUATION
        CALL INTDR(I*DR,M,RHO,DRHO,DM)
        KM1 = DR*DM
        KRHO1 = DR*DRHO
!FINDS K2 FOR EACH EQUATION
        CALL INTDR((I+.5)*DR,M+KM1/2.0,RHO+KRHO1/2.0,DRHO,DM)
        KM2 = DR*DM
        KRHO2 = DR*DRHO
!FINDS K3 FOR EACH EQUATION
        CALL INTDR((I+.5)*DR,M+KM2/2.0,RHO+KRHO2/2.0,DRHO,DM)
        KM3 = DR*DM
        KRHO3 = DR*DRHO
!FINDS K4 FOR EACH EQUATION
        CALL INTDR((I+1)*DR,M+KM3,RHO+KRHO3,DRHO,DM)
        KM4 = DR*DM
        KRHO4 = DR*DRHO
!SOLVES FOR M+1 AND RHO+1
        M = M+(KM1+2.0*KM2+2.0*KM3+KM4)/6.0
        RHO = RHO+(KRHO1+2.0*KRHO2+2.0*KRHO3+KRHO4)/6.0
        R = I*DR
!RETURNS A VALUE FOR THE ENERGY
        CALL EPS(RHO,EPSRHO)
        KINETIC = KINETIC+R*R*EPSRHO
        GRAV = GRAV+M*RHO*R
    END DO
!NEWTON-COTES QUADRATURE WITH EXTREMELY SMALL H
    KINETIC = KINETIC*DR
    GRAV = GRAV*DR
    CALL SCALE(YE,M,R,GRAV,KINETIC)
    RETURN
END SUBROUTINE

SUBROUTINE INTDR(R,M,RHO,DRHO,DM)
!EQUATIONS USED WHEN INTEGRATING WITH RESPECT TO THE RADIUS
IMPLICIT NONE
    REAL :: M           !MASS AT GIVEN RADIUS (IN)
    REAL :: RHO         !DENSITY !        RHO = 1200.0AT GIVEN RADIUS (IN)
    REAL :: R           !GIVEN RADIUS
    REAL :: DRHO        !DENSITY DERIVATIVE AT R (OUT)
    REAL :: DM          !MASS DERIVATIVE AT R (OUT)
    REAL :: X           !LOCAL VARIABLE TO CONVERT RHO
    REAL :: GAMMA       !LOCAL VARIABLE FOR GAMMA
    X = RHO**(1.0/3.0)
    GAMMA = X*X/SQRT(1.0+X*X)/3.0
    DRHO = -M*RHO/GAMMA/R/R
    DM = RHO*R*R
    RETURN
END SUBROUTINE

SUBROUTINE EPS(RHO,EPSRHO)
!EQUATION FOR EPSILON IN EQUATION II.10A. CONVERTS RHO -> X
IMPLICIT NONE
    REAL :: RHO             !RHO (IN)
    REAL :: EPSRHO          !EPSILON (OUT)
    REAL :: X
    X = RHO**(1.0/3.0)
    EPSRHO = 3.0*(X*(1+2.0*X*X)*SQRT(1+X*X)-LOG(X+SQRT(1+X*X)))/8.0
    RETURN
END SUBROUTINE

SUBROUTINE SCALE(YE,M,R,GRAV,KINETIC)
!INPUTS THE FINAL, UNSCALED VALUES, SCALES AND PRINTS
IMPLICIT NONE
    INTEGER, PARAMETER :: IKIND=SELECTED_REAL_KIND(P=15)
    REAL :: M           !FINAL MASS
    REAL :: R           !FINAL RADIUS
    REAL :: GRAV        !FINAL GRAVITATIONAL ENERGY
    REAL :: KINETIC     !FINAL KINETIC ENERGY
    REAL :: YE          !NUMBER OF ELECTRONS PER NUCLEON
    REAL :: R0          !SCALING FACTOR FOR RADIUS
    REAL :: M0          !SCALING FACTOR FOR MASS
    REAL (KIND=IKIND) :: E0 !SCALING FACTOR FOR ENERGY
    R0 = 0.011096*YE
    M0 = 2.857*YE*YE
    E0 = 2.7746E44_IKIND*YE**3
!E0 = 4*PI*G*RHO0*M0*R0^2 CONVERTED FROM ERGS TO JOULES
    PRINT *,'TOTAL MASS          =',M*M0*1.0_IKIND,'M0'
    PRINT *,'TOTAL RADIUS        =',R*R0*1.0_IKIND,'R0'
    PRINT *,'GRAVIATIONAL ENERGY =',-GRAV*E0,'JOULES'
    PRINT *,'KINETIC ENERGY      =',KINETIC*E0,'JOULES'
    PRINT *,'TOTAL ENERGY        =',(KINETIC-GRAV)*E0,'JOULES'
    PRINT *,
    RETURN
END SUBROUTINE
