PROGRAM EXERCISE2
!MODELS SHM WITH DY/DY=P AND
!DP/DT = -4YPI^2 WITH AN INITIAL VALUE OF
!P(0)=-1 & Y(0)=1 USING 1000 STEPS
!Y(T) = COS(2PI*T)-SIN(2PI*T)
!P(T) = -2PI*(SIN(2PI*T)+COS(2PI*T))
IMPLICIT NONE
    REAL :: Y,P,T
    REAL :: PI = 4.0*ATAN(1.0)

10  PRINT *,'ENTER A VALUE OF T'
    READ *,T
    P = -1.0
    Y = 1.0

    PRINT *,'Y EXACT =',COS(2.0*PI*T)-SIN(2.0*PI*T)/(2.0*PI)
    PRINT *,'P EXACT =',-2.0*PI*SIN(2.0*PI*T)-COS(2.0*PI*T)
    CALL RUNGEKUTTA(Y,P,T)
    PRINT *,'Y = ',Y
    PRINT *,'P = ',P

    GOTO 10
END PROGRAM

SUBROUTINE RUNGEKUTTA(Y,P,T)
!   USES FOURTH-ORDER RUNGE-KUTTA METHOD TO INTEGRATE
IMPLICIT NONE
    REAL :: T,H
    REAL :: P,Y
    REAL :: KY1,KY2,KY3,KY4
    REAL :: KP1,KP2,KP3,KP4
    REAL :: DY,DP
    INTEGER :: I

    H = T/1000.0
    DO I=0,999
!FINDS K1 FOR EACH VARIABLE
        CALL INTDT(I*H,Y,P,DY,DP)
        KY1 = H*DY
        KP1 = H*DP
!FINDS K2 FOR EACH VARIABLE
        CALL INTDT((I+.5)*H,Y+KY1/2.0,P+KP1/2.0,DY,DP)
        KY2 = H*DY
        KP2 = H*DP
!FINDS K3 FOR EACH VARIABLE
        CALL INTDT((I+.5)*H,Y+KY2/2.0,P+KP2/2.0,DY,DP)
        KY3 = H*DY
        KP3 = H*DP
!FINDS K4 FOR EACH VARIABLE
        CALL INTDT((I+1)*H,Y+KY3,P+KP3,DY,DP)
        KY4 = H*DY
        KP4 = H*DP
!SOLVES FOR Y+1 AND P+1
        Y = Y+(KY1+2.0*KY2+2.0*KY3+KY4)/6.0
        P = P+(KP1+2.0*KP2+2.0*KP3+KP4)/6.0
    END DO
    RETURN
END SUBROUTINE

SUBROUTINE INTDT(T,Y,P,DY,DP)
!   INTEGRATES P AND Y WITH RESPECT TO T
IMPLICIT NONE
    REAL :: T           !INDEPENDENT VARIABLES
    REAL :: Y,P         !DEPENDENT VARIABLES
    REAL :: DY,DP
    REAL :: PI = 4.0*ATAN(1.0)
    DP = -4.0*PI**2*Y
    DY = P
    RETURN
END SUBROUTINE


