name: On Push
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install deps
        run: >-
          python -m pip install --upgrade pip &&
          pip3 install -r requirements.txt &&
          mkdir -p $(python3 -m site --user-site) &&
          ln -s $(pwd) $(python3 -m site --user-site)
      - name: Lint python
        run: >-
          pylint --fail-under=4.46 **/*.py
      - name: Run tests
        run: >-
          python -m unittest discover tests/
